### ISSUE TITLE
In-context plugin bugs with latest release

### ISSUE THREAD

**Issue by jdimeo** [tolgee/tolgee-js#3090] opened 2022-08-30 18:14 UTC
- When switching languages, the screen rapidly reloads after a stack trace
![image](https://user-images.githubusercontent.com/1071438/187512450-27eaaf3c-4d69-4911-b1f7-0fbb5c9e3a6f.png)

- When picking languages, the language selection screen is unusually large/full screen and you can't see which languages you are picking
![image](https://user-images.githubusercontent.com/1071438/187512412-b9f8feb0-9349-4fea-bd49-40830ef00d59.png)

- When you do pick languages, the shown languages don't seem to reflect it

**Comment by jdimeo** [comment] 2022-09-01 17:58
I'm seeing now some 500 error codes when the plugin loads:

`https://app.tolgee.io/v2/projects/translations?languages=bn-BD&languages=ceb-PH&languages=e...=qug-EC&languages=qvo-EC&languages=sw-TZ&languages=war-PH&filterKeyName=edu_work_hours.base.prompt&ak=tgpak_haztm...`
returns:
```
{"code":"unexpected_error_occurred","params":["org.springframework.transaction.TransactionSystemException"]}
```

`https://app.tolgee.io/v2/projects/languages?size=1000&ak=tgpak_haztm...`
returns:
```
{"code":"unexpected_error_occurred","params":["org.springframework.dao.DataAccessResourceFailureException"]}
```

This is strange because when I click those links normally in the browser, they work just fine. But for some reason when the plugin does it AJAX, it creates these errors.

**Comment by stepan662** [comment] 2022-09-05 09:10
I was able to replicate and these were two errors caused by large amount of selected languages:
 1. UI select was getting too wide - fixed
 2. Backend timeouting - not fixed on BE yet, however I've put a limit to how many languages will be selected initialy, so it won't break on first opening

**Comment by stepan662** [comment] 2022-09-05 09:12
It's fixed in these two releases:
https://github.com/tolgee/tolgee-js/releases/tag/v4.9.1
https://github.com/tolgee/tolgee-js/releases/tag/v4.8.6

**Closed by stepan662** 2022-09-05 09:12 UTC

**Comment by jdimeo** [comment] 2022-09-05 11:45
THANK YOU @stepan662 ! The thing is, I never *want* to have so many available languages to each user :-) once we can limit permissions on languages more, our translators will only have access to about 6 languages max.

**Comment by stepan662** [comment] 2022-09-05 12:05
Yep, I understand.
