### ISSUE TITLE
MaterialUI tooltip component crashes in context editing

### ISSUE THREAD

**Issue by kasugaicrow** [tolgee/tolgee-js#1168] opened 2021-12-07 10:55 UTC
Hi,
inside my project I have a `Tooltip` component [(Tooltip)](https://v4.mui.com/components/tooltips/#tooltip) that wraps an icon and I'm trying to localize it. The simplified structure is as following:

```tsx
const t = useTranslate()
return (
  <Tooltip title={t("topbar.account")}>
    <IconButton>
      <AccountBox />
    </IconButton>
  </Tooltip>
)
```
The problem arises at the moment in which I hover the icon, the error returned is:
> Cannot read property 'attributes' of null

Under the hood Material translate the `tooltip` in a `div` so I can't see why it isn't working properly.
I already tried the `passToParent` and `tagAttributes` options.

Have you ever faced something similar? Can I provide you other useful infos?

Dependencies versions:
@tolgee/react: **2.8.0**
@tolgee/ui: **2.8.0**
react: **17.0.2**
material-ui: **4.11.3**

**Comment by JanCizmar** [comment] 2021-12-07 11:26
Hi!
Thanks for submitting. It's strange since we use exactelly the same stack and tooltips work fine.
Can you please provide a stacktrace of the error? Minimum example project would be also great.

**Comment by JanCizmar** [comment] 2021-12-07 11:46
OK, so I reproduced locally on sample project. Going to fix it.

**Comment by kasugaicrow** [comment] 2021-12-07 11:48
I was here writing the repro, glad to hear you managed to reproduce it! Let me know if you need any help.

**Comment by JanCizmar** [comment] 2021-12-07 12:31
It seems like this happens, because Material UI is removing the `title` attribute from the child while it renders the tooltip. I am looking into it, but if you need quick workaround, you can add aria-label attribute to the child element, so in-context localization stays working and use noWrap in the tooltips title attribute.
```
import './App.css';
import {Tooltip} from "@material-ui/core";
import {useTranslate} from "@tolgee/react";

function App() {
  const t = useTranslate()

  return (
    <div className="App">
      <header className="App-header">
        <Tooltip title={t({key: 'topbar.account', noWrap: true})}>
          <div aria-label={t({key: 'topbar.account'})}>Hello</div>
        </Tooltip>
      </header>
    </div>
  );
}

export default App;
```

**Comment by kasugaicrow** [comment] 2021-12-07 13:18
I didn't notice that Material UI was removing the `title` attribute, anyway I'm gonna use the workaround for the time being. Thanks!

**Comment by kasugaicrow** [comment] 2021-12-07 13:42
Do you have an account where I can test? Because I have another issue with the MaterialUI library and for the repro I need to link the api key. Actually I can create an account with a temp email. Is that ok?

**Comment by JanCizmar** [comment] 2021-12-07 13:46
Please open new issue for that :) Just add comment, that api key needs to be added. I will use my account to test it.

**Comment by JanCizmar** [comment] 2021-12-07 15:27
It's fixed in the PR, but I still recommend to use the workaround. Wit noWrap it will be wrapped, so the position tooltip will be counted with longer text and it's not going to be positioned well. 

![image](https://user-images.githubusercontent.com/18496315/145057601-a1dc8e29-3b8f-4cb6-8fea-36c9d900edac.png)

**Closed** 2021-12-07 18:38 UTC
Labels: bug
